from enum import Enum


class BrowserSessionStatus(str, Enum):
    CREATED = "CREATED"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHENTICATING = "AUTHENTICATING"
    AUTHENTICATED = "AUTHENTICATED"
    READY = "READY"
    EXECUTING = "EXECUTING"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class ExecutionStepState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    STARTING_BROWSER = "STARTING_BROWSER"
    NAVIGATING = "NAVIGATING"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHENTICATING = "AUTHENTICATING"
    INSPECTING_FORM = "INSPECTING_FORM"
    FORM_READY = "FORM_READY"
    FILLING = "FILLING"
    UPLOAD_IN_PROGRESS = "UPLOAD_IN_PROGRESS"
    PAUSED_FOR_USER = "PAUSED_FOR_USER"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    SUBMISSION_BLOCKED = "SUBMISSION_BLOCKED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class ChallengeType(str, Enum):
    NONE = "NONE"
    CAPTCHA = "CAPTCHA"
    BOT_CHECK = "BOT_CHECK"
    OTP_REQUIRED = "OTP_REQUIRED"
    TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    ACCESS_DENIED = "ACCESS_DENIED"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    UNKNOWN_CHALLENGE = "UNKNOWN_CHALLENGE"


class AuthStatus(str, Enum):
    AUTHENTICATED = "AUTHENTICATED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    UNKNOWN = "UNKNOWN"


class FieldActionType(str, Enum):
    FILL = "FILL"
    SELECT = "SELECT"
    CHECK = "CHECK"
    UPLOAD_RESUME = "UPLOAD_RESUME"
    CLICK_NEXT = "CLICK_NEXT"
    SKIP = "SKIP"


class FieldMatchStatus(str, Enum):
    MATCHED = "MATCHED"
    AMBIGUOUS = "AMBIGUOUS"
    UNKNOWN = "UNKNOWN"
    REQUIRES_USER_INPUT = "REQUIRES_USER_INPUT"
    UNSAFE_TO_AUTOFILL = "UNSAFE_TO_AUTOFILL"
