from app.schemas.user import UserBase, UserCreate, UserResponse
from app.schemas.resume import (
    EducationItem,
    ExperienceItem,
    ProjectItem,
    CertificationItem,
    ResumeProfile,
    ResumeBase,
    ResumeCreate,
    ResumeResponse,
    CandidateProfile,
)
from app.schemas.preferences import (
    UserPreferencesBase,
    UserPreferencesCreate,
    UserPreferencesUpdate,
    UserPreferencesResponse,
)
from app.schemas.job import (
    JobPostingBase,
    JobPostingCreate,
    JobPostingResponse,
    JobFilter,
    JobSearchQuery,
    SourceError,
    DiscoveryResult,
)
from app.schemas.matching import (
    HardFilterResult,
    JobMatchResult,
    MatchQuery,
    RankedJobsQuery,
    RankedJobsResponse,
)
from app.schemas.status_history import (
    StatusHistoryBase,
    StatusHistoryCreate,
    StatusHistoryResponse,
)
from app.schemas.state_machine import (
    ApplicationStateMachine,
    InvalidStateTransitionError,
    VALID_TRANSITIONS,
)
from app.schemas.application import (
    FormFieldValue,
    GeneratedAnswer,
    ReviewPackage,
    ApplicationBase,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationTransitionRequest,
    ApplicationResponse,
)

from app.schemas.connector import (
    PlatformType,
    ApplicationMethod,
    ConnectorCapabilities,
    ATSDetectionResult,
    ApplicationRoute,
    PlatformDetectResponse,
    ConnectorInfo,
)
from app.schemas.application_draft import (
    FieldType,
    FieldSource,
    QuestionCategory,
    ApplicationField,
    DraftCustomQuestion,
    CandidateApplicationContext,
    ApplicationDraft,
    ApplicationDraftCreateRequest,
    ApplicationDraftValidationResponse,
    ApplicationReviewPackageResponse,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserResponse",
    "EducationItem",
    "ExperienceItem",
    "ProjectItem",
    "CertificationItem",
    "ResumeProfile",
    "ResumeBase",
    "ResumeCreate",
    "ResumeResponse",
    "CandidateProfile",
    "UserPreferencesBase",
    "UserPreferencesCreate",
    "UserPreferencesUpdate",
    "UserPreferencesResponse",
    "JobPostingBase",
    "JobPostingCreate",
    "JobPostingResponse",
    "JobFilter",
    "JobSearchQuery",
    "SourceError",
    "DiscoveryResult",
    "HardFilterResult",
    "JobMatchResult",
    "MatchQuery",
    "RankedJobsQuery",
    "RankedJobsResponse",
    "StatusHistoryBase",
    "StatusHistoryCreate",
    "StatusHistoryResponse",
    "ApplicationStateMachine",
    "InvalidStateTransitionError",
    "VALID_TRANSITIONS",
    "FormFieldValue",
    "GeneratedAnswer",
    "ReviewPackage",
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationTransitionRequest",
    "ApplicationResponse",
    "PlatformType",
    "ApplicationMethod",
    "ConnectorCapabilities",
    "ATSDetectionResult",
    "ApplicationRoute",
    "PlatformDetectResponse",
    "ConnectorInfo",
    "FieldType",
    "FieldSource",
    "QuestionCategory",
    "ApplicationField",
    "DraftCustomQuestion",
    "CandidateApplicationContext",
    "ApplicationDraft",
    "ApplicationDraftCreateRequest",
    "ApplicationDraftValidationResponse",
    "ApplicationReviewPackageResponse",
]
